apiVersion: v1
kind: Service
metadata:
  name: nodejs-server-service
spec:
  type: NodePort
  selector:
    app: nodejs-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001

